# Generated by Django 3.1.7 on 2021-04-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pollkarapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
