# Generated by Django 3.1.7 on 2021-04-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pollkarapp', '0002_auto_20210406_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
